version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./containers/proxy/conf.d:/etc/nginx/conf.d:rw
      - ./containers/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./containers/proxy/html:/usr/share/nginx/html:rw
      - ./containers/proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - ./containers/proxy/certs:/etc/nginx/certs:rw
      - ./containers/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./containers/proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: postgres
    restart: always
    container_name: nextcloud-db
    networks:
      - nextcloud_network
    volumes:
      - ./containers/backend/data:/var/lib/postgresql/data/pgdata
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: <YOUR-POSTGRES-USER>
      POSTGRES_PASSWORD: <YOUR-POSTGRES-PASSWORD>
      PGDATA: /var/lib/postgresql/data/pgdata

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - ./containers/app/nextcloud:/var/www/html
      - ./containers/app/config:/var/www/html/config
      - ./containers/app/custom_apps:/var/www/html/custom_apps
      - ./containers/app/data:/var/www/html/data
      - ./containers/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: <YOUR-HOST>
      LETSENCRYPT_HOST: <YOUR-HOST>
      LETSENCRYPT_EMAIL: <YOUR-EMAIL>
      POSTGRES_DB: <YOUR-DB-NAME>
      POSTGRES_USER: <YOUR-DB-USER>
      POSTGRES_PASSWORD: <YOUR-DB-PASSWORD>
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: <YOUR-NEXTCLOUD-USER>
      NEXTCLOUD_ADMIN_PASSWORD: <YOUR-NEXTCLOUD-PASSWORD>
    restart: unless-stopped

networks:
    nextcloud_network:

